version: "3.9"

services:
  nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.config:/etc/conf.d/customer_proxy_settings.conf
    ports:
      - "80:80"
    networks:
      - ecommerce-network
  identity:
    image: quay.io/keycloak/keycloak:21.0.2
    command: ['start-dev --import-realm']
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: passthrough
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HTTP_PORT: 80
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./identity/themes/ecommerce/theme:/opt/keycloak/theme
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    driver: bridge
