version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ecommerce-network

  kibana:
    image: kibana:8.6.2
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "xpack.security.enabled=false"
    ports:
      - "5601:5601"
    networks:
      - ecommerce-network
    depends_on:
      - elasticsearch

networks:
  ecommerce-network:

volumes:
  esdata:
