backend:
  image:
    repository: ghcr.io/egikarakashi/ecommerce-product
    tag: latest

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  ingress:
    enabled: true
    host: api.ecommerce.local.com
    path: /product
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/ecommerce/product
  extraApplicationConfigPaths:
    - /opt/ecommerce/product/product-application.yaml
