package com.ecommerce.app.product.utils

object Constants {
    object ErrorCode {
        const val PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
        const val PRODUCT_OPTION_NOT_FOUND = "Product option %s is not found"
        const val PRODUCT_ATTRIBUTE_NOT_FOUND = "Product attribute %s is not found"
        const val PRODUCT_ATTRIBUTE_GROUP_NOT_FOUND = "Product attribute group %s is not found"

        const val CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
        const val BRAND_NOT_FOUND = "BRAND_NOT_FOUND"
        const val PARENT_CATEGORY_NOT_FOUND = "PARENT_CATEGORY_NOT_FOUND"
        const val MAKE_SURE_CATEGORY_DO_NOT_CONTAIN_CHILDREN = "MAKE_SURE_CATEGORY_DO_NOT_CONTAIN_CHILDREN"
        const val MAKE_SURE_CATEGORY_DO_NOT_CONTAIN_PRODUCT = "MAKE_SURE_CATEGORY_DO_NOT_CONTAIN_PRODUCT"
        const val PARENT_CATEGORY_CANNOT_BE_ITSELF = "PARENT_CATEGORY_CANNOT_BE_ITSELF"
        const val PRODUCT_ATTRIBUTE_VALUE_IS_NOT_FOUND = "PRODUCT_ATTRIBUTE_VALUE_IS_NOT_FOUND"
        const val THIS_PROD_ATTRI_NOT_EXIST_IN_ANY_PROD_ATTRI = "THIS_PROD_ATTRI_NOT_EXIST_IN_ANY_PROD_ATTRI"
        const val PRODUCT_ATTRIBUTE_IS_NOT_FOUND = "PRODUCT_ATTRIBUTE_IS_NOT_FOUND"
        const val SLUG_IS_DUPLICATED = "SLUG_IS_DUPLICATED"
        const val PRODUCT_TEMPLATE_IS_NOT_FOUND = "PRODUCT_TEMPLATE_IS_NOT_FOUND"

        const val MAKE_SURE_BRAND_DONT_CONTAINS_ANY_PRODUCT = "MAKE_SURE_BRAND_DONT_CONTAINS_ANY_PRODUCT"
        const val MAKE_SURE_PRODUCT_ATTRIBUTE_GROUP_DO_NOT_CONTAINS_ANY_PRODUCT_ATTRIBUTE =
            "Make sure product attribute group do not contains any product attribute"
        const val NAME_ALREADY_EXITED = "NAME_ALREADY_EXITED"
        const val PRODUCT_NOT_HAVE_VARIATION = "PRODUCT_NOT_HAVE_VARIATION"
        const val SLUG_ALREADY_EXISTED_OR_DUPLICATED = "SLUG_ALREADY_EXISTED_OR_DUPLICATED"
        const val SKU_ALREADY_EXISTED_OR_DUPLICATED = "SKU_ALREADY_EXISTED_OR_DUPLICATED"
        const val GTIN_ALREADY_EXISTED_OR_DUPLICATED = "GTIN_ALREADY_EXISTED_OR_DUPLICATED"
        const val PRODUCT_OPTION_VALUE_IS_NOT_FOUND = "PRODUCT_OPTION_VALUE_IS_NOT_FOUND"
        const val PRODUCT_COMBINATION_PROCESSING_FAILED = "PRODUCT_COMBINATION_PROCESSING_FAILED"
        const val NO_MATCHING_PRODUCT_OPTIONS = "NO_MATCHING_PRODUCT_OPTIONS"
    }
}
