name: rating service ci

on:
  push:
    branches: [main]
    paths:
      - 'rating/**'
      - '.github/workflows/rating-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  pull_request:
    branches: [main]
    paths:
      - 'rating/**'
      - '.github/workflows/rating-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  rating:
    uses: ./.github/workflows/backend-ci-template.yaml
    with:
      service: rating
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      ghcr-token: ${{ secrets.TOKEN }}
