name: recommendation service ci

on:
  push:
    branches: [main]
    paths:
      - 'recommendation/**'
      - '.github/workflows/recommendation-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  pull_request:
    branches: [main]
    paths:
      - 'recommendation/**'
      - '.github/workflows/recommendation-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  recommendation:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/backend-ci-template.yaml
    with:
      service: recommendation
    secrets: inherit
