name: search service ci

on:
  push:
    branches: [main]
    paths:
      - 'search/**'
      - '.github/workflows/search-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  pull_request:
    branches: [main]
    paths:
      - 'search/**'
      - '.github/workflows/search-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  search:
    uses: ./.github/workflows/backend-ci-template.yaml
    with:
      service: search
      docker-tags: ghcr.io/egikarakashi/spring-ecommerce-app/search:${{ github.sha }}
    secrets:
      ghcr_token: ${{ secrets.TOKEN }}
