name: tax service ci

on:
  push:
    branches: [main]
    paths:
      - 'tax/**'
      - '.github/workflows/tax-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  pull_request:
    branches: [main]
    paths:
      - 'tax/**'
      - '.github/workflows/tax-ci.yaml'
      - '.github/workflows/backend-ci-template.yaml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  tax:
    uses: ./.github/workflows/backend-ci-template.yaml
    with:
      service: tax
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      ghcr-token: ${{ secrets.TOKEN }}
